@baseUrl = http://localhost:8000

# python manage.py migrate
# python manage.py loaddata core/fixtures/articles.json
# python manage.py runserver

### all articles
GET {{baseUrl}}/api/articles/

### articles from page3
GET {{baseUrl}}/api/articles/?page=3

### articles from page5
GET {{baseUrl}}/api/articles/?page=5

### invalid page number
GET {{baseUrl}}/api/articles/?page=abc

### out of range page
GET {{baseUrl}}/api/articles/?page=999
